"""Add avatar_path to users

Revision ID: 582576f1ab29
Revises: b4a0b2ffe231
Create Date: 2026-08-25 21:36:07.670560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '582576f1ab29'
down_revision: Union[str, None] = 'b4a0b2ffe231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_path')
    # ### end Alembic commands ###
