"""Add is_profile to face_data

Revision ID: b4a0b2ffe231
Revises: d42b2e81294b
Create Date: 2026-08-24 16:12:56.675131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4a0b2ffe231'
down_revision: Union[str, None] = 'd42b2e81294b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'avatar',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('attendance_logs', 'attachment_url')
    op.add_column('face_data', sa.Column('is_profile', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('face_data', 'is_profile')
    op.add_column('attendance_logs', sa.Column('attachment_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('admins', 'avatar',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
