"""add avatar to admin

Revision ID: d42b2e81294b
Revises: e31b679e3d09
Create Date: 2026-07-27 21:50:26.677381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd42b2e81294b'
down_revision: Union[str, None] = 'e31b679e3d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'avatar')
    # ### end Alembic commands ###
