"""add_ml_person_id_and_nullable_embedding

Revision ID: e31b679e3d09
Revises: e878079a0f0a
Create Date: 2026-06-02 00:13:16.508407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e31b679e3d09'
down_revision: Union[str, None] = 'e878079a0f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('face_data', 'embedding_json',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('users', sa.Column('ml_person_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ml_person_id')
    op.alter_column('face_data', 'embedding_json',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
